<?php
coverflow(array(
  'demo/coverflow' => array(
    'attic.jpg',
    'aurora.jpg',
    'barbecue.jpg',
    'blackswan.jpg',
    'chess.jpg',
    'fire.jpg',
    'keyboard.jpg',
    'locomotive.jpg',
    'diveevo.jpg',
    'person.jpg',
    'rose.jpg',
    'seagull.jpg',
    'solarpower.jpg'
  )
));
?>